#!/usr/bin/bash

#git-create-version-tag <tag-name> <maven-module>
#git-create-version-tag java-utils-bom ../java-utils-bom

TAG=$1/v$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout -pl=$2)
mvn org.apache.maven.plugins:maven-scm-plugin:tag -Dtag=$TAG -DpushChanges=false -q
printf $TAG

